name: Test

on:
  pull_request:
    branches: ['main']

jobs:
  test:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
      env:
        PUBLIC_LOG_LEVEL: info
        PUBLIC_APP_ENV: development
        NODE_ENV: development
        PUBLIC_CF_TURNSTILE_KEY: ${{ secrets.PUBLIC_CF_TURNSTILE_KEY }}
        SECRET_CF_TURNSTILE_SECRET: ${{ secrets.SECRET_CF_TURNSTILE_SECRET }}
        PUBLIC_POCKETBASE_URL: ${{ secrets.PUBLIC_POCKETBASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install
      - name: Run your tests
        run: npx playwright test
        env:
          HOME: /root

  semantic-release:
    needs: test
    permissions:
      contents: write
      pull-requests: write
      issues: write
    name: 'Semantic Release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          semantic_version: 24.1.2
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/npm
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
